---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	calculator(calculator)
	rag(rag)
	general(general)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	router -.-> calculator;
	router -.-> general;
	router -.-> rag;
	calculator --> __end__;
	general --> __end__;
	rag --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
