"""RAG path — upload -> chunk -> embed (local) -> Chroma -> retrieve -> answer.

Embeddings use the free, local ``all-MiniLM-L6-v2`` model via
sentence-transformers, so no embedding API calls are made. Chunks are stored in
a persistent Chroma collection. The answer is generated by GPT-4.1 using ONLY
the retrieved chunks, which keeps it grounded and limits hallucination.
"""

from __future__ import annotations

import hashlib
import os
import re
from functools import lru_cache

from langchain_core.messages import HumanMessage, SystemMessage

from ..config import (
    CHROMA_COLLECTION,
    CHROMA_DIR,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    EMBEDDING_MODEL,
    RETRIEVE_TOP_K,
    get_llm,
)

_RAG_SYSTEM = (
    "You answer questions using ONLY the provided context from uploaded "
    "documents. If the answer is not contained in the context, say you could "
    "not find it in the documents — do not invent facts. Quote figures and "
    "policy terms exactly as written. Be concise."
)


@lru_cache(maxsize=1)
def _embedder():
    """Load the local sentence-transformers model once and cache it."""
    from sentence_transformers import SentenceTransformer

    return SentenceTransformer(EMBEDDING_MODEL)


@lru_cache(maxsize=1)
def _collection():
    """Return the persistent Chroma collection, creating it if needed."""
    import chromadb

    os.makedirs(CHROMA_DIR, exist_ok=True)
    client = chromadb.PersistentClient(path=CHROMA_DIR)
    # cosine space matches normalized MiniLM embeddings well.
    return client.get_or_create_collection(
        name=CHROMA_COLLECTION, metadata={"hnsw:space": "cosine"}
    )


def _embed(texts: list[str]) -> list[list[float]]:
    vecs = _embedder().encode(texts, normalize_embeddings=True)
    return [v.tolist() for v in vecs]


def chunk_text(text: str, size: int = CHUNK_SIZE, overlap: int = CHUNK_OVERLAP) -> list[str]:
    """Split text into overlapping character windows on paragraph/word edges."""
    text = re.sub(r"\s+\n", "\n", text).strip()
    if len(text) <= size:
        return [text] if text else []

    chunks: list[str] = []
    start = 0
    while start < len(text):
        end = min(start + size, len(text))
        # Prefer to break at a paragraph or sentence boundary near the window end.
        window = text[start:end]
        if end < len(text):
            for sep in ("\n\n", "\n", ". ", " "):
                idx = window.rfind(sep)
                if idx > size * 0.5:  # only break if it's not too early
                    end = start + idx + len(sep)
                    window = text[start:end]
                    break
        chunk = window.strip()
        if chunk:
            chunks.append(chunk)
        if end >= len(text):
            break
        start = max(end - overlap, start + 1)
    return chunks


def read_file(name: str, data: bytes) -> str:
    """Extract plain text from an uploaded file (.pdf, .txt, .md)."""
    lower = name.lower()
    if lower.endswith(".pdf"):
        import io

        from pypdf import PdfReader

        reader = PdfReader(io.BytesIO(data))
        return "\n\n".join((page.extract_text() or "") for page in reader.pages)
    # txt / md / anything decodable as text
    return data.decode("utf-8", errors="ignore")


def ingest(name: str, data: bytes) -> int:
    """Chunk, embed and store one document. Returns the number of chunks added.

    Chunk IDs are content-hashed so re-uploading the same file is idempotent
    (upsert) rather than creating duplicates.
    """
    text = read_file(name, data)
    chunks = chunk_text(text)
    if not chunks:
        return 0

    ids, metadatas = [], []
    for i, chunk in enumerate(chunks):
        h = hashlib.sha1(f"{name}:{i}:{chunk[:64]}".encode()).hexdigest()[:16]
        ids.append(f"{name}-{i}-{h}")
        metadatas.append({"source": name, "chunk": i})

    _collection().upsert(
        ids=ids,
        documents=chunks,
        embeddings=_embed(chunks),
        metadatas=metadatas,
    )
    return len(chunks)


def has_documents() -> bool:
    """True if at least one chunk is indexed."""
    try:
        return _collection().count() > 0
    except Exception:
        return False


def reset_documents() -> None:
    """Clear all indexed documents (used by the sidebar 'clear' action)."""
    import chromadb

    client = chromadb.PersistentClient(path=CHROMA_DIR)
    try:
        client.delete_collection(CHROMA_COLLECTION)
    except Exception:
        pass
    _collection.cache_clear()


def retrieve(question: str, k: int = RETRIEVE_TOP_K) -> list[dict]:
    """Return the top-k most similar chunks with their source metadata."""
    if not has_documents():
        return []
    res = _collection().query(
        query_embeddings=_embed([question]),
        n_results=k,
        include=["documents", "metadatas", "distances"],
    )
    hits = []
    docs = res.get("documents", [[]])[0]
    metas = res.get("metadatas", [[]])[0]
    dists = res.get("distances", [[]])[0]
    for doc, meta, dist in zip(docs, metas, dists):
        hits.append({"text": doc, "source": meta.get("source", "?"), "distance": dist})
    return hits


def answer_with_rag(question: str, k: int = RETRIEVE_TOP_K) -> tuple[str, list[dict]]:
    """Retrieve context and produce a grounded answer. Returns (answer, hits)."""
    hits = retrieve(question, k=k)
    if not hits:
        return (
            "No documents have been uploaded yet, so I can't search them. "
            "Upload a document in the sidebar and ask again.",
            [],
        )

    context = "\n\n---\n\n".join(
        f"[Source: {h['source']}]\n{h['text']}" for h in hits
    )
    prompt = (
        f"Context from uploaded documents:\n\n{context}\n\n"
        f"Question: {question}\n\n"
        "Answer using only the context above."
    )
    llm = get_llm()
    resp = llm.invoke([SystemMessage(content=_RAG_SYSTEM), HumanMessage(content=prompt)])
    return resp.content.strip(), hits
